### ISSUE TITLE
TrayIcon?

### ISSUE THREAD

**Issue by henrikruscon** [orchetect/MacControlCenterUI#6]
Fantastic work so far, solves a lot of my issues. Wondering if it would be possible to add ability to change tray icon (menu bar)? Right now it only accepts systemImages.

**Comment by orchetect** [comment]
Do you mean MenuBarExtra? Have you tried its overloads for custom images?

**Comment by henrikruscon** [comment]
Yeah that's what I mean, like for example here is the icon for Color Picker app (but it uses SF symbols, not custom image):
<img width="57" alt="CleanShot 2023-03-07 at 00 56 57@2x" src="https://user-images.githubusercontent.com/1430576/223283658-6b4d19ea-3643-49fc-941c-236531faa07e.png">

Not sure what you mean?

**Comment by orchetect** [comment]
Overloads mean different initializers. `MenuBarExtra` can take a custom image with one of the alternate initializers:

https://developer.apple.com/documentation/swiftui/menubarextra
