### ISSUE TITLE
Project files are corrupted 😩

### ISSUE THREAD

**Issue by Greg-Tichy** [orchetect/MacControlCenterUI#8]
xcode -> clone repository, opens it automatically, but in Project Navigator there are ***NO*** Project files visible! Next tried to compile source of MacControlCenterUIDemoApp. Unfortunately doesn't work, says file doesn't belong to current Scheme.  Probably it's true, but doesn't help any further.
To solve the issue I created a new Project under root folder and Xcode fixed(!) the Project above (the parent). All fine. 
BTW I have here Xcode 14.2 and latest Ventura as of today.

**Comment by orchetect** [comment]
I nuked DerivedData and cloned fresh and everything is fine. Xcode 14.3 on Ventura 13.3.
